### ISSUE TITLE
ClearCommandSystemTest Fails

### ISSUE THREAD

**Issue by WoodyLau** [CS2103JAN2018-F11-B1/main#154]
Tests when run right now for ClearCommandSystemTest, will pass through Travis but not through regular running, at least on my computer
I believe the problem is due to autocomplete. The test is that it types c then presses enter to run a clear through alias. With autocomplete, it autocompletes to clear instead.

**Comment by A0155428B** [comment]
alias test passes on my laptop

**Comment by WoodyLau** [comment]
Hm interesting, so if you comment out the other tests except the second last one, which is the alias test, it works?
When I try it, it types c, which flashes to clear, and then the test fails.

**Comment by WoodyLau** [comment]
Hm, now it's working.
